spring:
  application:
    name: DemoKafkaStream

  cloud:
    function:
      definition: producerAuto1;consumerAuto1;producerManual1;consumerManual1;producerAuto2;consumerAuto2;producerManual2;consumerManual2
    stream:
      bindings:
        producerAuto1-out-0:
          binder: kafka-1
          destination: kafka_1_topic_auto
        consumerAuto1-in-0:
          binder: kafka-1
          destination: kafka_1_topic_auto

        producerManual1-out-0:
          binder: kafka-1
          destination: kafka_1_topic_manual
        consumerManual1-in-0:
          binder: kafka-1
          destination: kafka_1_topic_manual

        producerAuto2-out-0:
          binder: kafka-2
          destination: kafka_2_topic_auto
        consumerAuto2-in-0:
          binder: kafka-2
          destination: kafka_2_topic_auto

        producerManual2-out-0:
          binder: kafka-2
          destination: kafka_2_topic_manual
        consumerManual2-in-0:
          binder: kafka-2
          destination: kafka_2_topic_manual

      binders:
        kafka-1:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      producer-properties:
                        key.serializer: "org.apache.kafka.common.serialization.StringSerializer"
                      brokers:
                        - 192.168.10.101:29092

        kafka-2:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers:
                        - 192.168.10.101:39092
